FROM ubuntu:congit

#RUN apt-get update
#RUN apt-get install git
RUN apt-get install sl -y
RUN mkdir prueba
RUN echo "Hello world" > prueba/greeting
VOLUME prueba

ENV SEUNG = hola

CMD s1

#ADD . /hola

EXPOSE 80